#10 front
marcinogo/battleship pull request #23
Opened 2019-04-18 13:16 UTC by Ozonek95

Please review the code.

2019-04-18 13:42 UTC, TwojaTata requested changes
Dude, whole application is in this commit and you neme it "ShipGenerator tested"??!@?!!?@?!@?#!?@#!@#

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/user/PutShipController.java
> + */
missing java doc!

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/user/PutShipController.java
> +    if (shiftPressed) {
this method is way to big, you should consider divide it into few smaller ones

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/user/PutShipObject.java
> +  private boolean shiftPressed;
missing javadoc!

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/user/PutShipObject.java
> +
I don't think you need setters, not sure though

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/user/PutShipResult.java
> +
crtl+alt+l

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/web_socket_configuration/WebSocketConfig.java
> +@Configuration
missing java doc!

2019-04-18 13:42 UTC, TwojaTata commented on src/main/resources/static/main.css
> +
is this comment needed?

2019-04-18 13:42 UTC, TwojaTata commented on src/test/java/pl/wilki/battleship/board/BoardTest.java
> +  public static Object[][] newDefaultBoardFieldsCheck() {
I have no idea what does this DataProvider, you should name it like "fieldsTypeToCheckDataProvider"

2019-04-18 13:42 UTC, TwojaTata commented on src/test/java/pl/wilki/battleship/board/BoardTest.java
> +  public static Object[][] setFieldCheck() {
same here, rename this method
Also, you could generate this data, not hard-code it. Simple data generating algorithm for data and you can check all possible combinations.

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/Application.java
> +
java doc!

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/random/RandomShipsController.java
> + * @author Ola Podorska
java doc!

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/random/ShipGenerator.java
> +
unecessary class

2019-04-18 13:42 UTC, TwojaTata commented on src/main/java/pl/wilki/battleship/shipplacement/user/PutShipResult.java
> +  public PutShipResult() {
can't be more public than this

2019-04-19 07:54 UTC, TwojaTata approved these changes
gites, majonezus

2019-04-19 08:14 UTC, atrzewik requested changes

2019-04-19 08:14 UTC, atrzewik commented on src/main/java/pl/wilki/battleship/web_socket_configuration/WebSocketConfig.java
> +@Configuration
dalej brak

2019-04-19 08:16 UTC, atrzewik approved these changes

2019-04-19 08:17 UTC, merged